#cmakedefine APPLICATION_NAME "${APPLICATION_NAME}"
#cmakedefine APPLICATION_VERSION "${APPLICATION_VERSION}"
#cmakedefine VKLIVE_ROOT "${VKLIVE_ROOT}"
#cmakedefine ZEP_SINGLE_HEADER "${ZEP_SINGLE_HEADER}"


